<?php use DynamicalWeb\Html\Functions; ?>
<nav class="topbar">
    <div class="container-fluid d-flex align-items-center justify-content-between h-100 px-4">
        <a class="topbar-brand fw-bold" href="<?php Functions::printRoute('home'); ?>">Liquid Elegance</a>
        <ul class="nav align-items-center">
            <li class="nav-item">
                <a class="nav-link" href="<?php Functions::printRoute('home'); ?>"><?php Functions::printl('nav_home'); ?></a>
            </li>
        </ul>
    </div>
</nav>
